//
// CookingRecord.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ユーザーの料理記録 */
public struct CookingRecord: Codable { 


    public var imageUrl: String?
    public var comment: String?
    public var recipeType: String?
    public var recordedAt: String?

    public init(imageUrl: String?, comment: String?, recipeType: String?, recordedAt: String?) {
        self.imageUrl = imageUrl
        self.comment = comment
        self.recipeType = recipeType
        self.recordedAt = recordedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case imageUrl = "image_url"
        case comment
        case recipeType = "recipe_type"
        case recordedAt = "recorded_at"
    }

}
