//
// CookingRecordsBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ユーザーの料理記録とページングを返却する */
public struct CookingRecordsBody: Codable { 


    public var pagination: Pagination?
    /** ユーザーの料理記録の配列 */
    public var cookingRecords: [CookingRecord]?

    public init(pagination: Pagination?, cookingRecords: [CookingRecord]?) {
        self.pagination = pagination
        self.cookingRecords = cookingRecords
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case pagination
        case cookingRecords = "cooking_records"
    }

}
