//
// Pagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ページングに関する情報 */
public struct Pagination: Codable { 


    public var total: Int?
    public var offset: Int?
    public var limit: Int?

    public init(total: Int?, offset: Int?, limit: Int?) {
        self.total = total
        self.offset = offset
        self.limit = limit
    }

}
