//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RxSwift



open class DefaultAPI {
    /**
     ユーザーの料理記録API
     
     - parameter offset: (query) オフセット (optional)
     - parameter limit: (query) リクエスト時指定の取得数 (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - returns: Observable<InlineResponse200>
     */
    open class func cookingRecordsGet(offset: Int? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = FunRecipeAPIAPI.apiResponseQueue) -> Observable<InlineResponse200> {
        return Observable.create { observer -> Disposable in
            cookingRecordsGetWithRequestBuilder(offset: offset, limit: limit).execute(apiResponseQueue) { result -> Void in
                switch result {
                case let .success(response):
                    observer.onNext(response.body!)
                case let .failure(error):
                    observer.onError(error)
                }
                observer.onCompleted()
            }
            return Disposables.create()
        }
    }

    /**
     ユーザーの料理記録API
     - GET /cooking_records
     - ユーザーの料理記録レコードを返すもの
     - parameter offset: (query) オフセット (optional)
     - parameter limit: (query) リクエスト時指定の取得数 (optional)
     - returns: RequestBuilder<InlineResponse200> 
     */
    open class func cookingRecordsGetWithRequestBuilder(offset: Int? = nil, limit: Int? = nil) -> RequestBuilder<InlineResponse200> {
        let path = "/cooking_records"
        let URLString = FunRecipeAPIAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "offset": offset?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<InlineResponse200>.Type = FunRecipeAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
